env:
  browser: true
  commonjs: true
  es2021: true
extends: google
overrides: [ ]
parserOptions:
  ecmaVersion: latest
rules: {
  linebreak-style: off,
  no-unused-vars: off,
  require-jsdoc: off,
  max-len: off,
  indent: [1, 4]

}
